// LOGIN AND SIGN UP TYPES

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED';

export const VERIFY_LOGIN = 'VERIFY_LOGIN';
export const VERIFY_LOGIN_SUCCESS = 'VERIFY_LOGIN_SUCCESS';
export const VERIFY_LOGIN_FAILED = 'VERIFY_LOGIN_FAILED';



export const SET_MENS_REGULAR = 'SET_MENS_REGULAR';
export const SET_START_LAST_PERIOD = 'SET_START_LAST_PERIOD';
export const SET_PERIOD_CYCLE_LENGTH = 'SET_PERIOD_CYCLE_LENGTH';
export const SET_PERIOD_LENGTH = 'SET_PERIOD_LENGTH';
export const SET_FIRST_TIME = 'SET_FIRST_TIME';


//User name
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_FIRST_TIME = 'SET_FIRST_TIME';

//Network availability
export const SET_NETWORK_ERROR_FALSE = "SET_NETWORK_ERROR_FALSE";
export const SET_NETWORK_ERROR_TRUE = "SET_NETWORK_ERROR_TRUE";

// POST NEW QUESTIONS

export const NEW_QUESTIONS = 'NEW_QUESTIONS';
export const NEW_QUESTIONS_SUCCESS = 'NEW_QUESTIONS_SUCCESS';
export const NEW_QUESTIONS_FAILED = 'NEW_QUESTIONS_FAILED';

